import esbuild from "esbuild";
import process from "process";
import { builtinModules } from 'node:module';
import fs from "fs";
import path from "path";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const vaultPathFile = ".obsidian-vault-path";
const vaultDest = fs.existsSync(vaultPathFile) ? fs.readFileSync(vaultPathFile, 'utf8').trim() : null;

const copyToVaultPlugin = {
	name: 'copy-to-vault',
	setup(build) {
		build.onEnd(() => {
			if (vaultDest) {
				const destDir = vaultDest;
				if (!fs.existsSync(destDir)) fs.mkdirSync(destDir, { recursive: true });
				
				['main.js', 'styles.css', 'manifest.json', '.hotreload'].forEach(file => {
					if (fs.existsSync(file)) {
						fs.copyFileSync(file, path.join(destDir, file));
					}
				});
				console.log(`\n✅ Arquivos copiados para o cofre Obsidian em: ${destDir}`);
			}
		});
	},
};

const jsContext = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	plugins: [copyToVaultPlugin],
});

const cssContext = await esbuild.context({
	entryPoints: ["styles/styles.css"],
	outfile: "styles.css",
	bundle: true,
	logLevel: "info",
	minify: prod,
	plugins: [copyToVaultPlugin],
});

if (prod) {
	await jsContext.rebuild();
	await cssContext.rebuild();
	process.exit(0);
} else {
	await jsContext.watch();
	await cssContext.watch();
}

